on:
  workflow_dispatch:
  push:
    
jobs:
  add-user:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/github-script@v5
        with: 
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |  
            const repo = "${{ github.repository }}".split('/')[1]
            const owner = "${{ github.repository_owner }}"
            const userFile = "users.yml"
            
            const script = require('${{ github.workspace }}/src/load-users.js')
            console.log(script({github, context, owner, repo, userFile}))            
