on:
  workflow_dispatch:
  push:
    
jobs:
  add-user:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v5
        with: 
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |  
            const repo = ${{ github.repository }}
            const owner = ${{ github.repository_owner }}
            try {
              const {data: yml} = await client.rest.repos.getContent({
                owner: owner,
                repo: name,
                path: 'users.yml'
              })
              console.log(yml)
            } catch (error) {
              core.debug(`No users.yml file found in repository: ${repo.name}`)
            }
